---
- name: Ensure user 'benjiao' exists
  become: true
  ansible.builtin.user:
    name: benjiao
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Ensure .ssh directory exists for benjiao
  become: true
  ansible.builtin.file:
    path: /home/benjiao/.ssh
    state: directory
    owner: benjiao
    group: benjiao
    mode: '0700'

- name: Fetch benjiao's authorized_keys from GitHub
  become: true
  ansible.builtin.get_url:
    url: https://github.com/benjiao.keys
    dest: /home/benjiao/.ssh/authorized_keys
    owner: benjiao
    group: benjiao
    mode: '0600'