---
- hosts: inventree.local
  vars:
    postgres_users_no_log: false
    postgresql_databases:
      - name: inventree
        owner: inventree
        encoding: UTF8
        locale: en_US.UTF-8
    postgresql_users:
      - name: inventree
        password: inventree
    postgresql_privs:
      - db: inventree
        roles: inventree  
        type: database
        privs: ALL
  roles:
    - role: benjiao.common
    - role: geerlingguy.postgresql
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: psycopg2-binary
            virtualenv: /opt/inventree/env
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - poppler-utils
        - fonts-dejavu-core
